name: 'Run octocov'
description: 'GitHub Action for octocov, a tool for collecting code coverage.'
branding:
  icon: 'octagon'
  color: 'gray-dark'
inputs:
  github-token:
    description: The GitHub token
    default: ${{ github.token }}
    required: false
  version:
    description: Version of octocov
    default: latest
    required: false
  checksum:
    description: Checksum of octocov
    default: ''
    required: false
  check-existence:
    description: Check for the existence of an existing octocov
    default: 'false'
    required: false
  config:
    description: Config path
    required: false
  workdir:
    description: Working directory (Deprecated)
    default: ''
    required: false
  work-dir:
    description: Working directory
    default: ''
    required: false
  install-dir:
    description: "Install directory"
    default: ''
    required: false
  args:
    description: Command line arguments of octocov
    default: ''
    required: false
runs:
  using: 'composite'
  steps:
    -
      uses: k1LoW/gh-setup@a2e69b734fd97adf7075e37b0f49b5dc5e1f44fc # v1.11.2
      with:
        repo: github.com/k1LoW/octocov
        github-token: ${{ inputs.github-token }}
        version: ${{ inputs.version }}
        bin-dir: ${{ inputs.install-dir }}
        bin-match: octocov
        checksum: ${{ inputs.checksum }}
        strict: true
        force: ${{ inputs.check-existence != 'true' }}
    -
      name: Run octocov
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const path = require('path');
          const inputs = ${{ toJSON(inputs) }};
          const toolpath = inputs['install-dir'] != '' ? path.join(inputs['install-dir'], 'octocov') : await io.which('octocov', true)
          const opt = `--config=${inputs.config} ${inputs.args}`
          const options = {};
          if (inputs.workdir != '') {
            core.warning('Using workdir: to set working directory is deprecated. Use work-dir: instead.')
          }
          options.cwd = inputs['work-dir'] != '' ? inputs['work-dir'] : inputs.workdir;
          await exec.exec(`${toolpath} ${opt}`, [], options)
      env:
        OCTOCOV_GITHUB_TOKEN: ${{ inputs.github-token }}
