name: Integration

on:
  push:

jobs:
  test-run:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./
        with:
          config: testdata/path/to/.octocov.yml
        env:
          ARTIFACT_NAME: "octocov-report-${{ matrix.os }}"
  test-run-with-work-dir:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./
        with:
          work-dir: testdata/path/to
        env:
          ARTIFACT_NAME: "octocov-report-with-work-dir-${{ matrix.os }}"
  test-run-with-install-dir:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./
        with:
          config: testdata/path/to/.octocov.yml
          install-dir: testdata/path/to
        env:
          ARTIFACT_NAME: "octocov-report-with-install-dir-${{ matrix.os }}"
