name: Integration

on:
  push:

jobs:
  test-run:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./
        with:
          config: testdata/path/to/.octocov.yml
        env:
          ARTIFACT_NAME: "octocov-report-${{ matrix.os }}"
  test-run-with-work-dir:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./
        with:
          work-dir: testdata/path/to
        env:
          ARTIFACT_NAME: "octocov-report-with-work-dir-${{ matrix.os }}"
  test-run-with-install-dir:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./
        with:
          config: testdata/path/to/.octocov.yml
          install-dir: testdata/path/to
        env:
          ARTIFACT_NAME: "octocov-report-with-install-dir-${{ matrix.os }}"
