name: Manage tag for v0
on:
  push:
    tags:
    - "v0+.[0-9]+.[0-9]+"
jobs:
  tag:
    name: Manage tag
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: docker-action
    -
      uses: haya14busa/action-update-semver@3f49a54b677d969c819c1c6ebea626a54dafe032 # v1.5.0
      with:
        major_version_tag_only: true
