name: Manage tag for v0
on:
  push:
    tags:
    - "v0+.[0-9]+.[0-9]+"
jobs:
  tag:
    name: Manage tag
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: docker-action
    -
      uses: haya14busa/action-update-semver@22a3666f9309f0d72ab0ea6c49b7a8019c1eab38 # v1.3.0
      with:
        major_version_tag_only: true
